apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-access-bot
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: bot
  ingress:
  - from:
    # We scrape the metrics from grafana-alloy
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana-alloy
