apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: limit-access-irc-relay
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: irc-relay
  ingress:
  - from:
    # Bot uses irc-relay to publish spam/revert feeds
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: bot
