name: Renovate CI
on: { pull_request: { } }
jobs:
  format-renovate-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: infrabits/ci-format-renovate-change@c54345e40a78eb353f83a7bd3670a3c796df0e86 # main
        with:
          github-token: ${{ github.token }}
