name: Renovate CI
on: { pull_request: { } }
jobs:
  format-renovate-change:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: infrabits/ci-format-renovate-change@a950244165f49e2596100fdf1514b75bb4813688 # main
        with:
          github-token: ${{ github.token }}
